# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-30 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(max_length=256)),
                ('page_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=256)),
                ('text', models.CharField(max_length=1024)),
                ('image', models.CharField(max_length=256)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='home.Page')),
            ],
        ),
        migrations.CreateModel(
            name='Textbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('founder', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='textbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='home.Textbook'),
        ),
    ]
