# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-13 22:42
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import home.custom
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(blank=True, max_length=256, null=True, unique=True)),
                ('page_num', home.custom.IntegerRangeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['page_num'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=256, null=True)),
                ('text', ckeditor.fields.RichTextField(null=True)),
                ('order', models.IntegerField(default=1)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='home.Page')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Textbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('founder', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=256, unique=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to=home.models.get_image_path)),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='textbook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='home.Textbook'),
        ),
    ]
