# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-01 17:10
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_title',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='text',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
