# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-08 17:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='page',
            order_with_respect_to='textbook',
        ),
    ]
