# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-21 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['page_num']},
        ),
        migrations.RenameField(
            model_name='page',
            old_name='textbook',
            new_name='t',
        ),
        migrations.AlterField(
            model_name='page',
            name='page_title',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='textbook',
            name='title',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
