# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-30 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20170130_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='page_num',
        ),
        migrations.AlterField(
            model_name='section',
            name='text',
            field=models.CharField(max_length=1024),
        ),
    ]
