# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-08 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20170208_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_title',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True),
        ),
    ]
