# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-21 20:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20170221_2029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='t',
            new_name='textbook',
        ),
    ]
