# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-30 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20170130_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='textbook',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=home.models.get_image_path),
        ),
    ]
