# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-08 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20170208_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='t',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='home.Textbook'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='page',
            order_with_respect_to=None,
        ),
        migrations.RemoveField(
            model_name='page',
            name='textbook',
        ),
    ]
