# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-08 19:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20170208_1925'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['page_num']},
        ),
    ]
