# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-31 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20170131_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='page_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
