# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-01 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_page_page_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='text',
            field=models.TextField(max_length=1024),
        ),
    ]
